### ISSUE TITLE
no "install" button in mesh router

### ISSUE THREAD

**Issue by wireks** [Ylianst/MeshCentralRouter#73]
Hello, when i download Mesh Router from MC there is to click install button:

![image](https://github.com/Ylianst/MeshCentralRouter/assets/58087362/e8986760-a928-4228-9e2b-ac8d4c57f24a)

but there is no Install button i Mesh Router...

![image](https://github.com/Ylianst/MeshCentralRouter/assets/58087362/b7e317bf-1fd3-4b54-9048-107afccd95b2)

**Comment by si458** [comment]
This is because it thinks the application is already installed somewhere else.
So best thing to do is to click the `Launch meshcentral router` button and see if the application loads up, 
If so then use task manager, and processes, and right click the meshcentralrouter.exe and click open file location

**Comment by wireks** [comment]
Yes, you have right. sorry.,
